export const FETCH_MOVIE_LIST = "FETCH_MOVIE_LIST";
export const FETCH_THEATER_LIST = "FETCH_THEATER_LIST";
export const SELECT_MOVIE = "SELECT_MOVIE";
export const SELECT_THEATER = "SELECT_THEATER";
