export const SWITCH_RAP = "switchRap";
export const FETCH_THEATER_LOGO = "FETCH_THEATER_LOGO";
export const FETCH_THEATER_LIST_DETAIL = "FETCH_THEATER_LIST_DETAIL";
export const GET_CODE_THEATER = "GET_CODE_THEATER";
export const REFRESH_CODE_THEATER = "REFRESH_CODE_THEATER";
export const LOADING = "LOADING";
